### ISSUE TITLE
[EPIC] Rollkit CI/CD Setup

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#112]
```[tasklist]
### Tasks
- [x] Check the state from https://github.com/celestiaorg/devops/issues/111
- [ ] https://github.com/celestiaorg/devops/issues/251
- [ ] https://github.com/celestiaorg/devops/issues/174
- [x] Discuss proposed changes with Rollkit Team
- [ ] https://github.com/celestiaorg/devops/issues/255
- [ ] https://github.com/celestiaorg/devops/issues/256
- [x] split build from test & coverage
```
