### ISSUE TITLE
[EPIC] CI/CD Improvements in celestia-app/node

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#113]
## Description 📜

Hello team,

The main goal of this epic is to improve the current CI/CD for app/node and speed up the process to create/update any chain.

That means that we'll provide the right tools for the teams in order to let them manage their own deployments, always supporting them, but not being a blocker for them.

During the epic, we should check the different approaches that app/node is using and fix in case of any issue

If you have more in mind, please, feel free to add them to the list 📝 

Thanks in advance!

--- 

### Some interesting articles 🔍

[Notion CICD](https://www.notion.so/celestiaorg/CICD-e908ba3db7a14214ad8c5d1838541836) -> check it
[CI/CD: Flow/Tagging/Deployment](https://www.notion.so/celestiaorg/CI-CD-Flow-Tagging-Deployment-ba0124114038449ab913b955ec8df6f5)

--- 

### Tasks 🔖

```[tasklist]
- [ ] https://github.com/celestiaorg/devops/issues/144
- [ ] https://github.com/celestiaorg/devops/issues/145
- [ ] https://github.com/celestiaorg/devops/issues/146
- [ ] https://github.com/celestiaorg/devops/issues/152
- [ ] https://github.com/celestiaorg/devops/issues/154
- [x] Check this, it might help to automate any chain: [19](https://github.com/celestiaorg/celestia-stack-internal/issues/19)
- [ ] https://github.com/celestiaorg/devops/issues/158
  - [ ] <https://github.com/celestiaorg/devops/issues/156>
- [ ] https://github.com/celestiaorg/devops/issues/187
- [x] Prepare the environment for the next epic (*robusta-nightly*)
- [x] https://github.com/celestiaorg/devops/issues/160
- [ ] https://github.com/celestiaorg/devops/issues/165
- [ ] https://github.com/celestiaorg/devops/issues/162
- [ ] https://github.com/celestiaorg/devops/issues/166
- [ ] https://github.com/celestiaorg/devops/issues/188
- [ ] https://github.com/celestiaorg/devops/issues/195
- [ ] https://github.com/celestiaorg/devops/issues/225
```

--- 

### Repository 🗂️

- [argocd-apps](https://github.com/celestiaorg/argocd-apps)
- [celestia-app](https://github.com/celestiaorg/celestia-app)
- [celestia-node](https://github.com/celestiaorg/celestia-node)

---

#### Issues 👨‍🔧

Closes: 

--- 

PS: *Please, feel free to update any part of the ticket, any suggestion/idea is always welcome* 😊 

---

Best 🚀 

Jose Ramon Mañes

**Comment by jrmanes** [comment]
update:

move the Grafana cloud to this epic: https://github.com/celestiaorg/devops/issues/130#issuecomment-1510953342
