### ISSUE TITLE
[EPIC] Robusta Nightly

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#114]
## Description 📜

Hello team,

In this epic, we will have to use the Robusta environments for making them available to execute test during the night.

From our notes: [link](https://www.notion.so/celestiaorg/Current-infra-status-and-next-steps-ab51902f4c2041fb8f10a347e4e50ce2#0e04f92c29b94d7894e5e9e51dc6a75e)

If you have more in mind, please, feel free to add them to the list 📝 

Thanks in advance!

--- 

### Some interesting articles 🔍

[Nightly test against our infra](https://www.notion.so/celestiaorg/Nightly-tests-against-our-infra-3efd7eecfc0440288ef1c33e04d1bb78)
[Nightly notes](https://www.notion.so/celestiaorg/Current-infra-status-and-next-steps-ab51902f4c2041fb8f10a347e4e50ce2#13fc91423855483fb7c31547694561a7)

--- 

### Tasks 🔖

- Nightly (Short)
- [x] #233
- [x] #234
- [x] #235
- [x] #250
- [x] #237
- [x] #238

  - ~short: Fully automated - on demand~ ✅
  - long: team initiated (usually by Git SHA, tags increase or emergency) - a long run
  - [x]  Requirements:
    - [x] Maximum 7 days live - also updated every 24h ✅
    - [x] Dashboards in Grafana per chain-id - autogenerated  ✅
      - [x] Collect:
        - [x] Metrics (using prometheus for it), done in the commits: ✅
            -  [b0928d8](https://github.com/celestiaorg/celestia-internal-tools/commit/b0928d8b917099776e58e0e549902f155cf7d3b0) 
            - [a57b32e](https://github.com/celestiaorg/celestia-internal-tools/commit/a57b32ec15c06624e3af44fb204b5ffbf5ad9c67)
            - [ce79cb4](https://github.com/celestiaorg/celestia-internal-tools/commit/ce79cb4334d2a72415394dd031b19b0966e90e85)
            - Results like: [Grafana](https://grafana.celestia-robusta.com/d/61490800ca1a9ac0d5b2e3f9b4d7370b89e131ad/monitoring-robusta-nightly-1?orgId=1&refresh=5s)
        - [x] Traces (done here: #261) ✅
        - [x] Logs (using loki) ✅
- [x] #261

- RCs (Long) -> we use the "normal" Robusta in this use case.
  - If breaking → new chain id
  - team initiated
    - [x] Requirements
      - [x] Maximum 30 days
        - [x] 0.0.X - long
        - [x] 0.X.0 - New
--- 

### Repository 🗂️

- [argocd-apps](https://github.com/celestiaorg/argocd-apps)
- [celestia-stack-internal](https://github.com/celestiaorg/celestia-stack-internal)

---

#### Issues 👨‍🔧

Closes: 

--- 

PS: *Please, feel free to update any part of the ticket, any suggestion/idea is always welcome* 😊 

---

Best 🚀 

Jose Ramon Mañes

**Comment by jrmanes** [comment]
hello @Bidon15 

regarding this epic, would you like to have anything else on it?
IIRC, this one was more about having the feature to run test against Robusta without assistance, keep a track about the events and having this kind of dynamic environments, isn't it?

thanks in advance! 😊

**Comment by jrmanes** [comment]
update:

- for solving the issue with the `TRUSTED_PEERS`, we thought about reusing the same keys for this nightly environment, deleting the `data + config` (to be sure in case of breaking changes)

- execute a cron at midnight (for example), to tear down the current environment and spin it up again with the latest main SHA for app/node

- I have to find the best approach to do it, using the AutoDevOps might require our approvals, and we don't want to do it, it should be autonomous

**Comment by Bidon15** [comment]
> hello @Bidon15
> 
> regarding this epic, would you like to have anything else on it? IIRC, this one was more about having the feature to run test against Robusta without assistance, keep a track about the events and having this kind of dynamic environments, isn't it?
> 

Yes, I want to use robusta nightly for these: 
- [ ] https://github.com/celestiaorg/test-infra/issues/158
- [ ] https://github.com/celestiaorg/test-infra/issues/173
- [ ] app fuzzing client(To be linked)

In addition, we will start introducing nightly fuzzing tests from app that @cmwaters is working on the client

**Comment by jrmanes** [comment]
update:

- [x] ~for solving the issue with the `TRUSTED_PEERS`, we thought about reusing the same keys for this nightly environment, deleting the `data + config` (to be sure in case of breaking changes)~
Done, we reuse the same keys for the nodes, problem solved.

- [x] ~execute a cron at midnight (for example), to tear down the current environment and spin it up again with the latest main SHA for app/node~
*The `CronJob` is triggered at midnight, it tears down the current robusta-nightly resources, gets the latest version of `celestia-app` & `celestia-node` and starts all the services again*

- [x] ~I have to find the best approach to do it, using the AutoDevOps might require our approvals, and we don't want to do it, it should be autonomous~
We can use the AutoDevOps to create the robusta-nightly files structure, but we won't need to approve any PRs. The `CronJob` inside the namespace will be autonomous to manage all the resources by itself.
The `CronJob` runs with a ServiceAccount which has the minimum amount of permissions to being able to manage the resources in Kubernetes (**only** in it's namespace)

**Comment by jrmanes** [comment]
update:

We should be able to execute test from TG against Robusta-Nightly, all the endpoints are available for doing it.
Ref: [link](https://github.com/celestiaorg/test-infra/issues/158#issuecomment-1521850013)

**Comment by jrmanes** [comment]
PR created here: https://github.com/celestiaorg/.github/pull/57

**Comment by jrmanes** [comment]
we'll take care of this topic once we have TG rewritten during Q3-4
