### ISSUE TITLE
[EPIC] Rollkit Tutorial testing

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#116]
- [ ] Document status quo
- [ ] Write DDR for tutorial testing
- [ ] Propose changes to Rollkit and DevRell
- [ ] Implement agreed changes for tutorial testing
- [ ] Document the new state of tutorial testing

cc. @celestiaorg/devrel

**Comment by jcstein** [comment]
This is where I had left off with the CI script: https://github.com/rollkit/docs/pull/113
