### ISSUE TITLE
[EPIC] Rollkit docker-compose

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#117]
- [ ] Document status quo of Rollkit docker-compose files
- [ ] Make changes to Rollkit docker-compose files
- [ ] Document the new state of Rollkit docker-compose files
