### ISSUE TITLE
[EPIC] TestGround Infra + Running tests

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#123]
## Description 📜

Hello team,

We have achieved results under this branch: 
https://github.com/celestiaorg/testground-infra/tree/jose/hackground-k8s-tf

If you have more in mind, please, feel free to add them to the list 📝 

Thanks in advance!

--- 

### Some interesting articles 🔍

[review-147](https://github.com/celestiaorg/test-infra/issues/147) 

--- 

### Tasks 🔖
What is needed the start running tests against the new infra implementation

```[tasklist]
**Goal: make it easy aka `helm chart`**

- [ ] https://github.com/celestiaorg/devops/issues/278
- [ ] https://github.com/celestiaorg/devops/issues/290
- [x] ~networking configuration in manual steps for instances~
- [x] ~add UUID to the IAM Service Role - use a variable to use it later in the cluster~
- [ ] https://github.com/celestiaorg/devops/issues/274
- [ ] https://github.com/celestiaorg/devops/issues/279
  - [x] <https://github.com/celestiaorg/devops/issues/277>
- [ ] https://github.com/celestiaorg/devops/issues/275
- [ ] https://github.com/celestiaorg/devops/issues/276
- [ ] https://github.com/celestiaorg/devops/issues/280
- [x] ~EKS limitations~ *we go with Kops for now, we can manage the CP (ControlPlane) by ourselves*
  - [ ] <https://github.com/celestiaorg/devops/issues/286>
- [x] influxdb deployment as a replica (not daemonset)
- [ ] https://github.com/celestiaorg/devops/issues/292
- [ ] https://github.com/celestiaorg/devops/issues/297
- [ ] https://github.com/celestiaorg/devops/issues/294
- [ ] https://github.com/celestiaorg/devops/issues/296
- [ ] https://github.com/celestiaorg/devops/issues/299
- [ ] https://github.com/celestiaorg/devops/issues/303
- [ ] https://github.com/celestiaorg/devops/issues/304
- [ ] https://github.com/celestiaorg/devops/issues/305
```

--- 

### Repository 🗂️

- [ ]( )

---

#### Issues 👨‍🔧

Closes: https://github.com/celestiaorg/test-infra/issues/147

--- 

PS: *Please, feel free to update any part of the ticket, any suggestion/idea is always welcome* 😊 

---

Best 🚀 

Jose Ramon Mañes

**Comment by jrmanes** [comment]
update:

Issues creating the cluster...
- EKS has some limitations, Alex talked with one of the previous maintainers and he gave us the "why", they decided to create the cluster with KOPS at the beginning... the CP (Control Plane) in EKS, is limited. With KOPS (or any other alternative), you can specify the CP resources/limits.
- Docker.sock: [link](https://github.com/celestiaorg/devops/issues/281#issuecomment-1527422173)
  - we have to find a workaround to start the tg-daemon.

**Comment by jrmanes** [comment]
update:

I'm able to execute tests against the new cluster 🚀 


![Image](https://user-images.githubusercontent.com/32740567/236868040-75976e10-ea9e-400d-a72f-86f2ed16d4e1.png)
![Image](https://user-images.githubusercontent.com/32740567/236868039-63b24934-384b-4b4a-b104-f6a678376546.png)
![Image](https://user-images.githubusercontent.com/32740567/236868041-874bbf00-dc63-49d1-ad46-6dbd1af1f175.png)
![Image](https://user-images.githubusercontent.com/32740567/236868038-6490bb01-31b6-4562-8069-afe8f606e689.png)
![Image](https://user-images.githubusercontent.com/32740567/236868042-c88cda04-7298-4767-980f-8f660adf95ee.png)

**Comment by jrmanes** [comment]
last but not least, scaling nodes tests (cluster flexibility)🥲

**Comment by jrmanes** [comment]
as a note/reminder.

in the future, it would be very nice to have: hardening the cluster + securing the services

we don't want to keep the cluster open for everybody (or bots)

**Comment by jrmanes** [comment]
https://github.com/celestiaorg/testground-infra/pull/2

**Comment by Bidon15** [comment]
can be closed once we merge https://github.com/celestiaorg/testground-infra/pull/2#pullrequestreview-1441650728
