### ISSUE TITLE
[EPIC] Integrate Rollkit Rollups to Kuberntes

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#125]
- [ ] Write plan how to achieve this and what the requirements we have
- [ ] Integrate Rollups to Kubernetes
- [ ] Document Rollups in Kubernetes

**Comment by Bidon15** [comment]
Moving to Q3 as we need to figure out knuu new features that accomplishes that 
cc: @smuu
