### ISSUE TITLE
[EPIC] Rollkit Integration tests

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#129]
```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/devops/issues/268
- [ ] https://github.com/celestiaorg/devops/issues/267
- [ ] https://github.com/celestiaorg/devops/issues/291
```

- [Framework Integration Testing](https://chat.openai.com/c/3e76731d-414b-4e41-9672-8e5730a029ef)
- [Library Integration Testing](https://chat.openai.com/c/d82cb594-1ad0-4f78-954a-14321184dcfb)
- [Library vs Framework](https://chat.openai.com/c/5822c781-5059-4621-a56b-540ead0e2732)
- [Rollkit Integration Tests](https://chat.openai.com/c/ba7b7620-1d2b-4621-8276-dc827cec4b48)

**Comment by Bidon15** [comment]
Can you please rework the chatgpt convos? The links are borked for me 😬

**Comment by smuu** [comment]
> Can you please rework the chatgpt convos? The links are borked for me grimacing

ChatGPT conversations are private and can't be shared directly. I linked them for my reference. Everything relevant to this or other issues will be added to the description.
