### ISSUE TITLE
[EPIC] Deployment Dashboard

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#130]
## Description 📜

Hello team,

This ticket was created with the idea to provide a Dashboard where we could find all the information related to a chain, for example, when we deploy a new robusta-X, we would like to know what version is running, number of nodes, URLs, etc...
Everything related to this chain.

If you have more in mind, please, feel free to add them to the list 📝 

Thanks in advance!

--- 

### Some interesting articles 🔍

[ ]( )

--- 

### Tasks 🔖

```[tasklist]
- [ ] https://github.com/celestiaorg/devops/issues/197
- [ ] https://github.com/celestiaorg/devops/issues/64
- [ ] https://github.com/celestiaorg/devops/issues/367
- [ ] https://github.com/celestiaorg/devops/issues/368
- [x] https://github.com/celestiaorg/devops/issues/412
- [ ] https://github.com/celestiaorg/devops/issues/425
- [ ] https://github.com/celestiaorg/devops/issues/447
- [ ] https://github.com/celestiaorg/devops/issues/453
- [ ] https://github.com/celestiaorg/devops/issues/471
- [ ] https://github.com/celestiaorg/devops/issues/474
```

--- 

### Repository 🗂️

- [ ]( )

---

#### Issues 👨‍🔧

Closes: 

--- 

PS: *Please, feel free to update any part of the ticket, any suggestion/idea is always welcome* 😊 

---

Best 🚀 

Jose Ramon Mañes

**Comment by jrmanes** [comment]
testing in k8s using ldflags within the dockerfile

**Comment by jrmanes** [comment]
update:

[dashboard](https://celestia.grafana.net/d/ea191537-e192-4aaa-a0a4-8860708db0f7/deploymentdashboard?orgId=1&refresh=5s&var-namespace=robusta-torch-1&from=now-5m&to=now)

**Comment by jrmanes** [comment]
pending to have the consensus metrics available
[deployment-dashboard](https://celestia.grafana.net/d/ea191537-e192-4aaa-a0a4-8860708db0f7/deploymentdashboard?orgId=1&refresh=5s)

**Comment by jrmanes** [comment]
update: 

- [versions dashboard](https://celestia.grafana.net/d/e256b4cc-79a2-453e-9aac-e2521a958576/versions-dashboard?orgId=1)
- [deployment-dashboard](https://celestia.grafana.net/d/ea191537-e192-4aaa-a0a4-8860708db0f7/deploymentdashboard?orgId=1&refresh=5s)

**Comment by jrmanes** [comment]
update:

arabica and mocha are empty, this is because until we will deploy the new versions, we don't have the metrics with the current ones

**Comment by Bidon15** [comment]
Clsoing as done
