### ISSUE TITLE
[EPIC] Helm Celestia-App/Node

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#131]
## Description 📜

Hello team,

The following epic was created in order to create a helm chart for our stacks, app & node.

In this epic, we will have to create the Helm charts and some tasks related to helm, such as, CICD, testing, publish releases, etc...

If you have more in mind, please, feel free to add them to the list 📝 

Thanks in advance!

--- 

### Some interesting articles 🔍

[What is Helm?](https://phoenixnap.com/kb/what-is-helm)
[From VMWare](https://tanzu.vmware.com/developer/guides/helm-what-is/#:~:text=Helm%20is%20a%20tool%20to,and%20scale%20applications%20as%20well.)
[helm.sh](https://helm.sh/)
[CNCF](https://www.cncf.io/blog/2020/08/26/why-do-devops-engineers-love-helm/)
[What and Why](https://www.bairesdev.com/blog/what-is-helm-and-why-you-should-be-using-it/)

--- 

### Tasks 🔖

- [x] Create a new repo for charts
- [x] celestia-app:
  - [x] https://github.com/celestiaorg/test-infra/issues/154
- [x] celestia-node: 
  - [x] https://github.com/celestiaorg/test-infra/issues/155
- [ ] Migrate the config files to helm templates and use the `values.yaml` for managing them (you can refer for instance to this [repo](https://github.com/celestiaorg/celestia-sre/tree/main/chains/arabica/limani/config))
- [ ] Check OCI as chart registry
- [ ] Create an initial version and publish it (check the helm registries)
- [ ] CICD
  - [ ] Setup the CI/CD pipelines 
  - [ ] Tags/Releases
- [ ] Tests if possible, check: [helm-unittest](https://github.com/jrmanes/helm-unittest)
- [ ] Internal use of the helm chars, point to a specific version and just use the `values.yaml` as you need.
- [ ] ArgoCD app as template
- [ ] Use ArgoCD for deploying the Helm Chart to Kubernetes
- [ ] Create the ArgoCD app

--- 

### Repository 🗂️

*To create*
- [celestia-helm-charts](https://github.com/celestiaorg/celestia-helm-charts)

---

#### Issues 👨‍🔧

Closes: 

--- 

PS: *Please, feel free to update any part of the ticket, any suggestion/idea is always welcome* 😊 

---

Best 🚀 

Jose Ramon Mañes

**Comment by jrmanes** [comment]
update:

@sysrex  is taking care of the Helm charts
the repo is [here](https://github.com/celestiaorg/celestia-helm-charts)

**Comment by Bidon15** [comment]
not a prio for this year
