### ISSUE TITLE
[EPIC] Replication of app & node

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#132]
```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/devops/issues/191
- [ ] Write a plan for data replication and fast-sync
- [ ] Discuss plan with DevOps and dev teams
- [ ] Implement replication of app & node
- [ ] Document replication of app & node
```

Ref: https://github.com/celestiaorg/devops/issues/228

Move to devops:
https://github.com/celestiaorg/celestia-stack-internal/issues/23
https://github.com/celestiaorg/celestia-stack-internal/issues/24

**Comment by smuu** [comment]
https://miro.com/app/board/uXjVMTmRiPQ=/

![image](https://user-images.githubusercontent.com/18609909/231425795-41cf03d8-d0d6-4f04-bc34-1407fe9d2fa5.png)

**Comment by Bidon15** [comment]
Maybe beginning of August to kick-start

**Comment by smuu** [comment]
Done with the deployment of lunaroasis
