### ISSUE TITLE
[EPIC] SecretManager

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#133]
## Description 📜

Hello team,

We are using 1Password for managing all our credentials.
The idea with this EPIC is to connect 1pass to k8s and manage all the secrets from 1pass, then, we'll inject them as a secret to the cluster.

If you have more in mind, please, feel free to add them to the list 📝 

Thanks in advance! 🚀 

Jose Ramon Mañes

--- 

### Some interesting articles 🔍

- [1pass](https://github.com/1Password)
- [1pass-operator](https://github.com/1Password/onepassword-operator#deploy-with-helm)
- [connect-helm-charts](https://github.com/1Password/connect-helm-charts)
- [docs](https://developer.1password.com/docs/connect/)
- [k8s-inyector](https://developer.1password.com/docs/connect/k8s-injector/)

--- 

### Tasks 🔖

```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/devops/issues/420
- [ ] https://github.com/celestiaorg/devops/issues/423
- [ ] https://github.com/celestiaorg/devops/issues/421
- [ ] https://github.com/celestiaorg/devops/issues/436
- [ ] https://github.com/celestiaorg/devops/issues/437
- [ ] https://github.com/celestiaorg/devops/issues/438
- [ ] https://github.com/celestiaorg/devops/issues/439
- [ ] https://github.com/celestiaorg/devops/issues/440
- [ ] https://github.com/celestiaorg/devops/issues/272
- [ ] https://github.com/celestiaorg/devops/issues/446
- [ ] https://github.com/celestiaorg/devops/issues/501
- [ ] https://github.com/celestiaorg/devops/issues/452
- [ ] https://github.com/celestiaorg/devops/issues/499
- [x] all the devs have an account now
```

--- 

### Repository 🗂️

- [internal-tools](https://github.com/celestiaorg/celestia-internal-tools/tree/main)

---

#### Issues 👨‍🔧

Closes: 

--- 

PS: *Please, feel free to update any part of the ticket, any suggestion/idea is always welcome* 😊 

---

Best 🚀 

Jose Ramon Mañes

**Comment by jrmanes** [comment]
check: https://team-celestia.1password.com/integrations/infrastructure-secrets?type=kubernetes

**Comment by jrmanes** [comment]
update: 

we can close this as done
