### ISSUE TITLE
[EPIC] Terraform State Management

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#134]
## Description 📜

ℹ️  *low priority*

Hello team,

We need to migrate the Terraform State to TF Cloud, as we are currently using AWS S3 for that, we can use the free tier and keep it simple in the cloud.

If you have more in mind, please, feel free to add them to the list 📝 

Thanks in advance!

--- 

### Some interesting articles 🔍

[ ]( )

--- 

### Tasks 🔖

```[tasklist]
### Tasks
- [x] Invite team members
- [x] Migrate state for the clusters
- [x] https://github.com/celestiaorg/devops/issues/417
- [ ] https://github.com/celestiaorg/devops/issues/418
- [ ] https://github.com/celestiaorg/devops/issues/419
- [ ] https://github.com/celestiaorg/devops/issues/415
- [ ] https://github.com/celestiaorg/devops/issues/416
```

--- 

### Repository 🗂️

- [terraform-k8s](https://github.com/celestiaorg/terraform-k8s)

---

#### Issues 👨‍🔧

Closes: 

--- 

PS: *Please, feel free to update any part of the ticket, any suggestion/idea is always welcome* 😊 

---

Best 🚀 

Jose Ramon Mañes

**Comment by jrmanes** [comment]
https://developer.hashicorp.com/terraform/tutorials/state/cloud-migrate
