### ISSUE TITLE
[EPIC] K8S Workshop

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#135]
- [ ] Figure out what we want in K8S to teach to the teams
- [ ] Prepare slides for k8s slides
- [ ] Prepare exercises for k8s workshop
- [ ] Perform k8s workshop
- [ ] Gather feedback from k8s workshop
