### ISSUE TITLE
Pin common workflows to a version

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#140]
Common workflows and actions are using the `main` branch currently. As those are under development, they could introduce breaking changes. Therefore, we should use versions from now on to track updates and changes. Dependabot should create a PR once a new version is available.

```[tasklist]
### Tasks
- [x] Create a release in `.github` repo (https://github.com/celestiaorg/.github/releases/tag/v0.1.0)
- [x] Pin all usage of common workflows to this release (https://github.com/celestiaorg/celestia-app/pull/1595 & https://github.com/celestiaorg/celestia-node/pull/2005)
- [ ] https://github.com/celestiaorg/devops/issues/184
```

**Comment by smuu** [comment]
Release draft: https://github.com/celestiaorg/.github/releases/edit/untagged-a581b95d04dcb6ec8ba1
