### ISSUE TITLE
Grafana Cloud - Migration/Centralization

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#197]
## Description 📜

Hello team,

We have found some issues with the Grafana Operator, it's missing the feature for setting up SSO.

After the DevOps weekly sprint meeting, we have decided to review Grafana Cloud instead, and keep everything in one place.

If you have more in mind, please, feel free to add them to the list 📝 

Thanks in advance!

--- 

### Some interesting articles 🔍

[ ]( )

--- 

### Tasks 🔖

- [x] Ship the data to Grafana Cloud
- [ ] Review the data sources and label the different clusters by id
- [ ] Dashboards as code

--- 

### Repository 🗂️

- [celestia-internal-tools](https://github.com/celestiaorg/celestia-internal-tools/)

---

#### Issues 👨‍🔧

Closes: 

--- 

PS: *Please, feel free to update any part of the ticket, any suggestion/idea is always welcome* 😊 

---

Best 🚀 

Jose Ramon Mañes

**Comment by Bidon15** [comment]
Closing as done
