### ISSUE TITLE
Cleanup stack & tools

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#199]
Once the development in stack-internal, internal-tools, and external-tools is more or less done, we should clean up and refactor the repos.

```[tasklist]
### Tasks
- [ ] Clean up/refactor stack-internal repo
- [ ] Clean up/refactor internal-tools repo
- [ ] Clean up/refactor external-tools repo
- [ ] Clean up/refactor argocd repo
```

**Comment by smuu** [comment]
Q4, just cleaning up
