### ISSUE TITLE
devops: Update Ansible Role - Bootstrappers

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#216]
## Description 📜

Hello team,

Just as a reminder:

Please update the Ansible Role with the latest version + new updates in the config, we have to recreate the config due to a breaking change.

Use as reference one of the current bootstrappers, there, you'll find the new updates.

If you have more in mind, please, feel free to add them to the list 📝 

Thanks in advance!

--- 

### Some interesting articles 🔍

[ ]( )

--- 

### Tasks 🔖

- [x] Update the docker-compose.yaml
- [x] Update the peers ids
- [x] Add the ENV VAR -> [CELESTIA_BOOTSTRAPPER](https://github.com/celestiaorg/celestia-node#environment-variables)

--- 

### Repository 🗂️

- [ansible-roles](https://github.com/celestiaorg/ansible-roles/tree/main/bootstrappers/)

---

#### Issues 👨‍🔧

Closes: 

--- 

PS: *Please, feel free to update any part of the ticket, any suggestion/idea is always welcome* 😊 

---

Best 🚀 

Jose Ramon Mañes

**Comment by jrmanes** [comment]
update:

branch changes here: [link](https://github.com/celestiaorg/ansible-roles/tree/jose/update-resoruces)

commit: [here](https://github.com/celestiaorg/ansible-roles/commit/f2ffebdd5534f4c07bd69bc4bcd905d4caacda6c)


pending to test it in a VM to verify it
