### ISSUE TITLE
[EPIC]: Mocha bootstrappers migration to K8s

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#239]
```[tasklist]
### Tasks
- [ ] Setup a new cluster 
- [ ] Migrate keys from existing mocha bootstrappers
- [ ] Setup Dashboards 
- [ ] Setup Alarming
- [ ] Sunset old bootstrappers / Cleanup
```

**Comment by Bidon15** [comment]
Done
