### ISSUE TITLE
robusta/stress: integrate fuzz client into filling part of robusta-release

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#249]
Currently, we have a simple script for filling robusta. 
In order to achieve stress testing in robusta-releases for celestia-node, we need to: 

```[tasklist]
### Tasks
- [ ] Take the fuzzing client from this PR https://github.com/celestiaorg/celestia-app/pull/1613
- [ ] Include it in the rotation to the PFBs
- [ ] Get the blocks to max possible sizes
- [ ] Ideally leave the chain producing big blocks for 3~5 days
```
