### ISSUE TITLE
Testing workflow for Rollkit

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#258]
Triggered by Release & CI workflow created in https://github.com/celestiaorg/devops/issues/259

```[tasklist]
### Tasks
- [x] Go Mod Tidy Check
- [x] Coverage
- [x] Unit Tests
- [x] Unit Tests with Race Detector
- [x] Integration Tests (another Epic: https://github.com/celestiaorg/devops/issues/129)
```

Ref: https://github.com/celestiaorg/celestia-node/blob/main/.github/workflows/go-ci.yml
