### ISSUE TITLE
Release & CI workflow for Rollkit

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#259]
```[tasklist]
### Tasks
- [x] Triggered on main, PRs, and version tags
- [x] Call linting workflow implemented in https://github.com/celestiaorg/devops/issues/257
- [x] Call testing workflow implemented in https://github.com/celestiaorg/devops/issues/258
- [x] Call proto lint and generate (See https://github.com/celestiaorg/celestia-app/blob/main/.github/workflows/proto.yml)
- [x] When triggered manually, it creates a release (major, minor, or patch)
```
  
Ref: https://github.com/celestiaorg/celestia-node/blob/main/.github/workflows/ci_release.yml
