### ISSUE TITLE
Housekeeping workflow for Rollkit

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#260]
PR: https://github.com/rollkit/rollkit/pull/905

```[tasklist]
### Tasks
- [x] Assigns PR and issues to the creator
- [x] Adds PR and issues to the project board
- [x] Adds random reviewer from the list
- [x] Adds `triage` label to new issues without tags
- [ ] Adds `external` label to issues and PRs not created by GitHub team member
- [ ] Adds `bot` label to PRs from Dependabot
- [x] Fails if PR is not labeled with a label from a list
- [ ] (Adds tags dependent on strings in the title)
```

Ref:
- [Housekeeping workflow](https://github.com/celestiaorg/.github/blob/main/.github/workflows/reusable_housekeeping.yml)
- [label automation](https://github.com/celestiaorg/celestia-node/blob/main/.github/workflows/issue-label-automation.yml)
- [required labels](https://github.com/celestiaorg/celestia-node/blob/main/.github/workflows/labels.yml)

Closes https://github.com/celestiaorg/devops/issues/255
