### ISSUE TITLE
[EPIC]: Integration test framework / Robusta per PR

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#291]
Introduction 🧐 
---

Inspiring from the [work done for this PR](https://github.com/celestiaorg/celestia-app/pull/1586) and talks with @smuu on integration testing for rollkit, I've seen a possibility for @celestiaorg/devops to create a unified integration framework for all 3 repos(app/node/rollkit).

Requirements 📝 
---

Here are the set of requirements that we need to accomplish in order to make _**running tests per PR/nightly/release**_: 

- test pods know which version of celestia-app/node/rollkit sw they are running
- main puppeteer to control the orchestration of test pods
- scheduling of test pods (init/running/terminating) is on the main puppeteer
- scheduling should be based on user's test-case (not all at once) 
- testing rolling updates is possible

Benefits of robusta-k8s for integration level tests 🥇 
---

1. HW resources allocation will not be a bummer for most of teams to trust test results
2. The go-client of k8s allows support of scheduling pods on whatever timeline the user wants 
3. In any given moment, user's can just execute a command inside the test pod if needed

Notes 📜 
---

1. We don't need to worry about network simulation here
2. GA Integration should be kept in mind when designing this minimal framework 
3. Main puppeter is the instantiation of the test-case itself(i.e. like testify)

Main Puppeteer 🎎 
---

```[tasklist]
### Tasks
- [x] Connects to Scaleway Robusta K8s cluster
- [x] Tells the cluster under a specific namespace which deployments to schedule
- [ ] Fetches all the IP:Ports of the pods (grpc/rpc/rest/etc.)
- [x] Force destroys the pods at the end of the test-case's go-context
- [x] Holds an api-client request/response to the GA API
```

**Comment by Bidon15** [comment]
cc: @celestiaorg/devops @cmwaters @nashqueue

**Comment by Bidon15** [comment]
Sample use-case after discussing with @cmwaters how app team could use this: 

Test-Case XYZ: 

- tell the cluster to schedule 4 consensus validators
- feed each of them with specific configs
- fetch all 4 IP:ports
- start fuzzing all 4 validators with TXs 
- check there are no errors 
- destroy the run 
- report back to ci job

**Comment by Bidon15** [comment]
Note: 

- PR tests are scheduled by unique namespaces to achieve max parallelisation 
- Scaleway auto-scaler enabled
- L instances 🧐

**Comment by jrmanes** [comment]
update:

from the weekly meeting:
a nice to have: https://github.com/celestiaorg/devops/issues/298

**Comment by Bidon15** [comment]
Closing as done.
