### ISSUE TITLE
feat: Robusta-PR - CRD

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#298]
## Description 📜

Hello team,

ℹ  *This ticket is created as a reminder, a nice to have in the future, so low priority at the moment.*

The original ticket is: [devops-291](https://github.com/celestiaorg/devops/issues/291).

The idea behind this ticket is to improve the previously mentioned and make it more Kubernetes native, modifying it in order to make it as a CRD([Custom Resource Definition](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/)).

If you have more in mind, please, feel free to add them to the list 📝 

Thanks in advance!

---

## Rewind, what is a CRD? ⏮️

Let's start with the beginning, a Custom Resource is an object that extends the Kubernetes API or allows you to introduce your own API into a cluster.

So, a CustomResourceDefinition (CRD) defines the name and structure of your custom resource that you want to add to the cluster.

*To summarize, a CRD is a way to extend the Kubernetes API and make it more flexible.*

---

### Okay sounds great, but what benefits bring us? 🧐

Based on the requirements that we have to create the service [here](https://github.com/celestiaorg/devops/issues/291), we will have a more native integration with the `client-go` library, this will allow us to communicate against the Kubernetes API.

Also, it will provide us with some features such as validation, defaulting, OpenAPI Schema, and we'll be able to have the status in the CLI using `kubectl` and doing something like `kubect get robusta-prs` (or whatever we name it), defining our custom columns.

On the other hand, one important thing that I can see is the way that we will deploy/invoke this service, every team will have the capacity to define their own manifest (YAML), with their custom fields, specifying the number of nodes, versions, adding metadata, etc... meaning that the entrypoint (input data) to the cluster, will be a simple `yaml` file.

And we'll have the CRD(operator), deployed in the cluster, so, once they apply their manifest, the operator will be in charge of doing all the required actions.

---

### Pros & Cons 📈📉

**Pros:**

- **Automation**: CRDs can automate the management of complex applications and workflows on Kubernetes, reducing the need for manual intervention.
- **Customization**: CRDs allow you to define your own API resources, giving you the flexibility to tailor Kubernetes to your specific needs and use cases.
- **Scalability**: They can help you scale your applications and workloads in a consistent and repeatable manner.
- **Reusability**: Reused across different applications and workloads, reducing the amount of development and maintenance effort required.

**Cons:**

- **Complexity**: Building an Operator with CRDs can be complex, *and requires a deep understanding of Kubernetes concepts and architecture*.
- **Learning curve**: It might require a significant investment in learning and training.
- **Maintenance**: They require some maintenance, as the Kubernetes API evolves and changes.
- **Debugging**: Debugging CRDs and Operators can be difficult, particularly when errors occur across multiple layers of the Kubernetes stack.

Overall, CRDs and Operators can be a powerful tool for managing complex applications and workflows on Kubernetes, but they require careful planning, development, and maintenance to be effective.

--- 

### Why we should consider it? ⚖️

As we have mentioned before, migrating the service `robusta-pr` as a CRD, it has a lot of sense, as we are going to use this service mainly in Kubernetes, we will have better integration and also, and we will provide an easy way to interact with it to our development teams (the YAML manifests).

We could consider it as "another DevOps team member", at the end the CRDs are also called `operators`, meaning that they are in charge of doing some actions in the cluster, managing resources, and providing some feedback to our, automating the manual process in code.

--- 

### Some interesting articles 🔍

- [kubernetes.io](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/)
- [why they are useful](https://thenewstack.io/kubernetes-crds-what-they-are-and-why-they-are-useful/)
- [k8s-crds](https://spacelift.io/blog/kubernetes-crd)
- [create a crd](https://able8.medium.com/create-a-simple-kubernetes-custom-resource-and-crd-with-kubectl-f2a73e166f5d)
- [how to](https://www.airplane.dev/blog/kubernetes-crds-custom-resource-definitions)
- [Kubernetes Operators](https://www.redhat.com/rhdc/managed-files/cl-oreilly-kubernetes-operators-ebook-f21452-202001-en_2.pdf)

--- 

### Tasks 🔖

- [ ] Gather the requirements and input data that we will need 
- [ ] Create the CRD project
- [ ] Migrate the logic from the current service to the new one
- [ ] Testing it

--- 

### Repository 🗂️

<to define>
- [ ]( )

---

#### Issues 👨‍🔧

Closes: 

--- 

PS: *Please, feel free to update any part of the ticket, any suggestion/idea is always welcome* 😊 

---

Best 🚀 

Jose Ramon Mañes

**Comment by jrmanes** [comment]
won't do it, we are using knuu as a native Go test for these kinds of tests
