### ISSUE TITLE
HTTP server with the router

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#342]
```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/devops/issues/345
- [ ] https://github.com/celestiaorg/devops/issues/346
- [ ] https://github.com/celestiaorg/devops/issues/347
- [ ] https://github.com/celestiaorg/devops/issues/350
- [ ] https://github.com/celestiaorg/devops/issues/348
- [ ] https://github.com/celestiaorg/devops/issues/351
```

**Comment by jrmanes** [comment]
done ✅
