### ISSUE TITLE
feat: spread the config between peers

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#351]
once you have the trusteed peers ids,

```[tasklist]
### Tasks
- [x] https://github.com/celestiaorg/devops/issues/354
- [ ] https://github.com/celestiaorg/devops/issues/353
- [ ] https://github.com/celestiaorg/devops/issues/355
```

**Comment by jrmanes** [comment]
we can get the addresses from the FNs without any manual interaction 👌
