### ISSUE TITLE
[EPIC]: Arabica CI/CD improvements

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#36]
This epic contains all issues we want to finish in order to have an efficient ci/cd pipeline for the arabica devnet

### Upgrade

- [x] https://github.com/celestiaorg/devops/issues/45
- [x] https://github.com/celestiaorg/devops/issues/49

### Docker

- [x] https://github.com/celestiaorg/devops/issues/37
- [x] https://github.com/celestiaorg/devops/issues/38

### Streamlined deployment

- [x] https://github.com/celestiaorg/devops/issues/39
- [ ] https://github.com/celestiaorg/devops/issues/43
- [ ] https://github.com/celestiaorg/devops/issues/44

### Others

- [ ] https://github.com/celestiaorg/devops/issues/42

**Comment by Bidon15** [comment]
Grooming 10/03/2023: Migrate #42 #43 #44 into a separate epic - @Bidon15
