### ISSUE TITLE
Expose/Get versions running

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#368]
Get the versions in a easy way:

```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/devops/issues/369
- [ ] https://github.com/celestiaorg/devops/issues/370
- [ ] https://github.com/celestiaorg/devops/issues/371
- [ ] https://github.com/celestiaorg/devops/issues/401
- [ ] https://github.com/celestiaorg/devops/issues/402
- [ ] https://github.com/celestiaorg/devops/issues/413
```

**Comment by jrmanes** [comment]
update:
subtasks are blocked...

**Comment by jrmanes** [comment]
close as done ✅
