### ISSUE TITLE
jaeger: deploy it as a cluster

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#372]
we're having issues as a simple instance

```[tasklist]
### Tasks
- [x] deployed as a cluster in a separate ns
- [x] deployed as a cluster in robusta-26 ns
- [x] create an extra full node and point to the cluster svc
- [x] add it to the argocd-apps repo
- [x] argocd-apps added
- [x] deploy it as an argocd-app
```

**Comment by jrmanes** [comment]
![Screenshot 2023-06-29 at 07 15 44](https://github.com/celestiaorg/devops/assets/32740567/2c52c688-43bf-407d-a04f-96f737013eb3)

**Comment by jrmanes** [comment]
- deployed as a cluster in a separate ns ✅
- deployed as a cluster in robusta-26 ns ✅
- create an extra full node and point to the cluster svc WIP

**Comment by jrmanes** [comment]
create an extra full node and point to the cluster svc ✅

it works fine, the jaeger can get the metrics from the new full-21 (it has in it's otel config -> the `jeager-cluster-collector` svc:

![Screenshot 2023-06-29 at 09 40 14](https://github.com/celestiaorg/devops/assets/32740567/54c09a6e-fb57-4c07-a196-b176b337b49d)

**Comment by jrmanes** [comment]
removing this extra full-21 node

**Comment by jrmanes** [comment]
pending to merge

**Comment by jrmanes** [comment]
jaeger seems to be stable atm, i've deployed it as a cluster, storing the data in Cassandra (3 replicas)

and the collector was scale to 3 (+ HPA 3<->10)

**Comment by jrmanes** [comment]
![Screenshot 2023-06-29 at 11 12 51](https://github.com/celestiaorg/devops/assets/32740567/64ccb48d-a38c-458e-bcdf-eadf088097be)

![Screenshot 2023-06-29 at 11 13 04](https://github.com/celestiaorg/devops/assets/32740567/b4f23c92-ad81-439e-ade5-4aa254a1959d)
