### ISSUE TITLE
refactor: internal-stack -> create chain_base

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#383]
in the stack-internal 
create a deactivated/chain_base folder to use it as a base template, instead of using robusta-2
```[tasklist]
### Tasks
- [x] https://github.com/celestiaorg/devops/issues/386
- [ ] https://github.com/celestiaorg/devops/issues/387
- [ ] https://github.com/celestiaorg/devops/issues/388
- [ ] https://github.com/celestiaorg/devops/issues/389
```

**Comment by jrmanes** [comment]
update autodevops script to use the base chain
