### ISSUE TITLE
robusta-64

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#391]
```[tasklist]
### Tasks
- [x] robusta-64
- [x] Each can be setup with
- [x] 1 consensus-validator
- [x] 2 consensus-full
- [x] disable metrics - keep only 1BN/1FN
- [x] 4 BNs
- [x] 20 FNs
- [x] jaeger
- [x] gen hash + trusted peer list
- [x] reset chain - start it today from scracth - recreate ns
- [x] which fills blocks to 64 ODS size
```

**Comment by jrmanes** [comment]
https://jaeger-robusta-64.celestia-robusta.com/



cc: @renaynay

**Comment by jrmanes** [comment]
gen hash: `1898358D49F43AE4F1C7B7DB64910C6513406BB01B4F99147D4D39156134E5C9`

**Comment by jrmanes** [comment]
```
"da-bridge-1-0": "/dns/da-bridge-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWHyqh2bVYX92kgEcw5RduCbEkFLQxv9eikLWFWNnpdem9",
"da-bridge-2-0": "/dns/da-bridge-robusta-64-2.celestia-robusta.com/tcp/2121/p2p/12D3KooWSdjyV3gGUkESUBuuvdytutGAy1udP6ufXWaAfz9CQ74n",
"da-bridge-3-0": "/dns/da-bridge-robusta-64-3.celestia-robusta.com/tcp/2121/p2p/12D3KooWRHBW4PV3f4FEGHT4xznAJpggKqLaeV2Js6QGzQy6NZHM",
"da-bridge-4-0": "/dns/da-bridge-robusta-64-4.celestia-robusta.com/tcp/2121/p2p/12D3KooWNNMzzfP9w5hnb9DfiYwk1seeLifXPMjNMa7UsnMcnV4J",
"da-full-1-0": "/dns/da-full-1-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWPbKzgTvDkhBsFrnw1W68ZcDpVgAQx4mkWTDV8vxZPm5Y",
"da-full-2-0": "/dns/da-full-2-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWQKH3SZa91qf8E9nypgHtDLL8Feh95uyfD3rdrApyP2GT",
"da-full-3-0": "/dns/da-full-3-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWA6R4KgLHcH38g5dzqY3wKybwdrmnRcrw1p2UtWUrRSgC",
"da-full-4-0": "/dns/da-full-4-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWGDQhu1gusZ21ySzpHyUJPZWatjsuwreJKj2HdEBzFiGj",
"da-full-5-0": "/dns/da-full-5-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWEAjz1UpR2GcRRijLARj2CEpL3XaCMW719UeTG7Yc2DNN",
"da-full-6-0": "/dns/da-full-6-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWSF75bGEpbmeHjBmzbv1tLaYXHJ5CatGJF6mKmFHedkv9",
"da-full-7-0": "/dns/da-full-7-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWKHggKcbZKynfYbiLCxhZde4sc9kkxDKbi1cTUs97mEUX",
"da-full-8-0": "/dns/da-full-8-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWGaH4M1vQTKJjRYRvxq8dJhmUPZsg982kA2yTjyamVHzK",
"da-full-9-0": "/dns/da-full-9-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWDRfMTK3xTwpLFqyVPcHdYSqj2jaPMzS2xgZAjvbwkzSf",
"da-full-10-0": "/dns/da-full-10-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWAsFE8iQqgkcDmL3vu6Qzqr2mZVrE1j4NizjgjCw3U9PK",
"da-full-11-0": "/dns/da-full-11-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWR8r9pdy4v7cemGrZwfK7auwCX2hF46EmFZ8tnioFMdny",
"da-full-12-0": "/dns/da-full-12-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWMPzenwUgjF7T6BjJtcy2VgJkt1qi5Rudt82XHuMczWCE",
"da-full-13-0": "/dns/da-full-13-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWP3eDFCaEVTxuTUqMXS5JjEaxTcT3awy8mU9VbwgmJoFt",
"da-full-14-0": "/dns/da-full-14-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWQEKAgAnXgYr4HxUGizKJwmpr2Qrb8jirYRbRuGdjdDEp",
"da-full-15-0": "/dns/da-full-15-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWQhUaj6a4GtGtaJz6uM8FuTSNGpRNjeALYUQx6QUfzuHm",
"da-full-16-0": "/dns/da-full-16-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWJfAbsjmx1d5XWhEhsMQtqxT95zBfifnjLYgatwWZZwzY",
"da-full-17-0": "/dns/da-full-17-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWQeFRV2pi9kiTsfRWi8CA5N87ZjBvxNDfx4Uqdbk3nAW2",
"da-full-18-0": "/dns/da-full-18-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWF9dPKCPokBZ7r7d1q9TUFxq4xmMP1L2RixrNHTzZZvs1",
"da-full-19-0": "/dns/da-full-19-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWCMNqrFK4fV7vjtNA4iugjGEwjuPRATcAwWo15BT3WreS",
"da-full-20-0": "/dns/da-full-20-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWP4J2A8AUU8ahGGCDbCDQwAGzfrdTSD2JDi8GcbvyzPW3"
````

**Comment by jrmanes** [comment]
we have to reset it, so, skip previous messages

**Comment by jrmanes** [comment]
hash: `5EAD527709E46B3D348E166289BE10560CC300D6DE8D429F341D9618445F3CE1`

**Comment by renaynay** [comment]
@jrmanes can you also provide some of the BN and FN multiaddrs? 

🙏🏻

**Comment by jrmanes** [comment]
```json
{
    "da-bridge-1-0": "/dns/da-bridge-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWASZkRzE7wyAMRKNWcJ9ht2ghXt5z1G2dkJ1pTSMogjDd",
    "da-bridge-2-0": "/dns/da-bridge-robusta-64-2.celestia-robusta.com/tcp/2121/p2p/12D3KooWPmD1yMMRj6GYwFRYuqNheGt3beneDYuAcZP12EuB2mDK",
    "da-bridge-3-0": "/dns/da-bridge-robusta-64-3.celestia-robusta.com/tcp/2121/p2p/12D3KooWGpW4Y8zCkdLouc1k1gaSB9bjrjyzMVrEAEZbc5ZQNvRg",
    "da-bridge-4-0": "/dns/da-bridge-robusta-64-4.celestia-robusta.com/tcp/2121/p2p/12D3KooWAxgcb97tcHG3sXhCGyFartqKqgDd9KSiLVGT5wT1Z624",
    "da-full-1-0": "/dns/da-full-1-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWEQ3y28d5xZ7WiTUwoSBaWK4iKHisZrEK2fjv9XE6afde",
    "da-full-2-0": "/dns/da-full-2-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWHNUWgetMBYmsAFXVuEhp4ekNTJiiZqMw96ceXwTdCAk4",
    "da-full-3-0": "/dns/da-full-3-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWFRPnTBY337qCkNXENorjh4akfr9VmW2LT1aBu4Tje11Q",
    "da-full-4-0": "/dns/da-full-4-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWNHt9tHpR5pxd4Tm1jsy1coQn9fe3uLsbtw4y6CwePYj5",
    "da-full-5-0": "/dns/da-full-5-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWBDVtH4submC1gpvuS7UW2H59L2tLSVox2fE6rsBp56zr",
    "da-full-6-0": "/dns/da-full-6-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWF3ygvSmCjRQG1L284xe6pKjKKuimNyhy2F4YpE8vPxiT",
    "da-full-7-0": "/dns/da-full-7-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWCFKEo8EzQLNpeLV5fpDSyKrHE9TLjR4EfXHfQrGfrKQ1",
    "da-full-8-0": "/dns/da-full-8-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWBU1fadeSL6aYoUZC43RAqKB6xykrfY2BWEBX3qoDzGxa",
    "da-full-9-0": "/dns/da-full-9-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWT1VFffM9yzJBL7KyQeNuNUv6gBMUp64j4yXeiposxqx6",
    "da-full-10-0": "/dns/da-full-10-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWC7dGJbeQ6LbieyyGr2XJQQws52k13dgQ4nysjGVC3EPC",
    "da-full-11-0": "/dns/da-full-11-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWE4CiCNExR9t1JuqZ1u6i6yfJUxt5U5ABqv37VRVWGPJU"
    "da-full-12-0": "/dns/da-full-12-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWNeJjU8z35F1unV6AqEj8hpVA6SStzNtF9HsNU9EwVEPc",
    "da-full-13-0": "/dns/da-full-13-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWBWBTJpoSgQ5bTFcEY4buXfaWbMiQw7Fqyd7kDcSkJkWS",
    "da-full-14-0": "/dns/da-full-14-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWHnvQVhK1RgNRbkcB4zdeekrBpCe57j4eBDvMqmyQ3xYp",
    "da-full-15-0": "/dns/da-full-15-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWDzH1ynSBXPCszsX2MRP5yPrwC2uiPUZ4JKxXco9H7UMA",
    "da-full-16-0": "/dns/da-full-16-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWKG1hmhpcYhRXrtZBfbFJr2jyNXLnUq6V4gYJmUb7SZSr",
    "da-full-17-0": "/dns/da-full-17-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWFjyiDY4PPNUD73r2gFQe5zyiLrp7w6kMQZGYsvnZJwFT",
    "da-full-18-0": "/dns/da-full-18-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWBUHw2pZdjMjBJ3t9Xm63K4iPvS7rBjSgRMxwN4Ss5Hey",
    "da-full-19-0": "/dns/da-full-19-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWAB3cnj456nFAFVnwCrifAQPgGDGRYXV5zYEdQ56w9itP",
    "da-full-20-0": "/dns/da-full-20-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWH8cqyZwarQvgdKta6HSjxfEeJY2aSGRaVsbqmwurXmud"
}
```

**Comment by jrmanes** [comment]
we're filling the blocks, let's keep this ticket open for now

**Comment by jrmanes** [comment]
https://jaeger-robusta-64.celestia-robusta.com/

**Comment by Bidon15** [comment]
for robusta-128 
https://pyroscope-robusta-128.celestia-robusta.com/

**Comment by Bidon15** [comment]
for grafana: 

https://celestia.grafana.net/dashboards/

**Comment by Bidon15** [comment]
> ```json
> {
>     "da-bridge-1-0": "/dns/da-bridge-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWASZkRzE7wyAMRKNWcJ9ht2ghXt5z1G2dkJ1pTSMogjDd",
>     "da-bridge-2-0": "/dns/da-bridge-robusta-64-2.celestia-robusta.com/tcp/2121/p2p/12D3KooWPmD1yMMRj6GYwFRYuqNheGt3beneDYuAcZP12EuB2mDK",
>     "da-bridge-3-0": "/dns/da-bridge-robusta-64-3.celestia-robusta.com/tcp/2121/p2p/12D3KooWN2P7VhQnSN2i9apkYctLr88j21UA1eNSkwcA12exGoxW",
>     "da-bridge-4-0": "/dns/da-bridge-robusta-64-4.celestia-robusta.com/tcp/2121/p2p/12D3KooWAxgcb97tcHG3sXhCGyFartqKqgDd9KSiLVGT5wT1Z624",
>     "da-full-1-0": "/dns/da-full-1-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWEQ3y28d5xZ7WiTUwoSBaWK4iKHisZrEK2fjv9XE6afde",
>     "da-full-2-0": "/dns/da-full-2-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWHNUWgetMBYmsAFXVuEhp4ekNTJiiZqMw96ceXwTdCAk4",
>     "da-full-3-0": "/dns/da-full-3-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWFRPnTBY337qCkNXENorjh4akfr9VmW2LT1aBu4Tje11Q",
>     "da-full-4-0": "/dns/da-full-4-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWNHt9tHpR5pxd4Tm1jsy1coQn9fe3uLsbtw4y6CwePYj5",
>     "da-full-5-0": "/dns/da-full-5-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWBDVtH4submC1gpvuS7UW2H59L2tLSVox2fE6rsBp56zr",
>     "da-full-6-0": "/dns/da-full-6-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWF3ygvSmCjRQG1L284xe6pKjKKuimNyhy2F4YpE8vPxiT",
>     "da-full-7-0": "/dns/da-full-7-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWCFKEo8EzQLNpeLV5fpDSyKrHE9TLjR4EfXHfQrGfrKQ1",
>     "da-full-8-0": "/dns/da-full-8-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWBU1fadeSL6aYoUZC43RAqKB6xykrfY2BWEBX3qoDzGxa",
>     "da-full-9-0": "/dns/da-full-9-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWT1VFffM9yzJBL7KyQeNuNUv6gBMUp64j4yXeiposxqx6",
>     "da-full-10-0": "/dns/da-full-10-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWC7dGJbeQ6LbieyyGr2XJQQws52k13dgQ4nysjGVC3EPC",
>     "da-full-11-0": "/dns/da-full-11-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWE4CiCNExR9t1JuqZ1u6i6yfJUxt5U5ABqv37VRVWGPJU"
>     "da-full-12-0": "/dns/da-full-12-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWNeJjU8z35F1unV6AqEj8hpVA6SStzNtF9HsNU9EwVEPc",
>     "da-full-13-0": "/dns/da-full-13-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWBWBTJpoSgQ5bTFcEY4buXfaWbMiQw7Fqyd7kDcSkJkWS",
>     "da-full-14-0": "/dns/da-full-14-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWHnvQVhK1RgNRbkcB4zdeekrBpCe57j4eBDvMqmyQ3xYp",
>     "da-full-15-0": "/dns/da-full-15-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWDzH1ynSBXPCszsX2MRP5yPrwC2uiPUZ4JKxXco9H7UMA",
>     "da-full-16-0": "/dns/da-full-16-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWKG1hmhpcYhRXrtZBfbFJr2jyNXLnUq6V4gYJmUb7SZSr",
>     "da-full-17-0": "/dns/da-full-17-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWFjyiDY4PPNUD73r2gFQe5zyiLrp7w6kMQZGYsvnZJwFT",
>     "da-full-18-0": "/dns/da-full-18-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWBUHw2pZdjMjBJ3t9Xm63K4iPvS7rBjSgRMxwN4Ss5Hey",
>     "da-full-19-0": "/dns/da-full-19-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWAB3cnj456nFAFVnwCrifAQPgGDGRYXV5zYEdQ56w9itP",
>     "da-full-20-0": "/dns/da-full-20-robusta-64.celestia-robusta.com/tcp/2121/p2p/12D3KooWH8cqyZwarQvgdKta6HSjxfEeJY2aSGRaVsbqmwurXmud"
> }
> ```

updated da-bridge-3

**Comment by Bidon15** [comment]
new da bridge 5 with pr-2463 badger v4
``` 
"da-bridge-5-0": "/dns/da-bridge-robusta-64-5.celestia-robusta.com/tcp/2121/p2p/112D3KooWNYZvYJQKg9xS29ry6r6aGwNRm9CXSfVLCfiyTzhbLMq4"
```

https://pyroscope-robusta-64.celestia-robusta.com/?query=celestia.da-node.inuse_space%7BpeerId%3D%2212D3KooWNYZvYJQKg9xS29ry6r6aGwNRm9CXSfVLCfiyTzhbLMq4%22%7D&from=now-5m&rightQuery=celestia.da-node.inuse_space%7B%7D&leftQuery=celestia.da-node.inuse_space%7B%7D

**Comment by Bidon15** [comment]
12D3KooWMEY2xrCsvXRMzw86mWpyLtop1aDTX4BfDUgYvHCXXgh7

**Comment by Bidon15** [comment]
new da bridge 7 with [latest main - 60a949e]https://github.com/celestiaorg/celestia-node/pkgs/container/celestia-node/109034060?tag=60a949e
``` 
"da-bridge-7-0": "/dns/da-bridge-robusta-64-7.celestia-robusta.com/tcp/2121/p2p/12D3KooWCJGvvvD1auaVGLx1rymPmTc87hUhdCdc4pEqB19i9b5n"
```

**Comment by jrmanes** [comment]
close as done, as we have removed the chains already
