### ISSUE TITLE
expose node version via otel endpoint

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#401]
```[tasklist]
### Tasks
- [x] adding a third package to import version & metrics on it - circle dependency if not
```

```[tasklist]
### Requirements
- [x] [ ] collect build info (Slava PR) -> [PR-2468](https://github.com/celestiaorg/celestia-node/pull/2468)
- [x] [ ] expose it as single gauge, in otel that has all info set to it attributes. *No need to add it to prometheus, since our direct prometheus usage is a temporary workaround to allow libp2p metrics. We want to move all metric to otel at some point.*
- [x] [ ] clean up global attributes of hotel
```

```[tasklist]
### Tasks on our side:
- [ ] https://github.com/celestiaorg/devops/issues/405
- [ ] https://github.com/celestiaorg/devops/issues/406
- [ ] https://github.com/celestiaorg/devops/issues/407
```

**Comment by jrmanes** [comment]
update:

node team is unifying build info through ldflags 
https://github.com/celestiaorg/celestia-node/pull/2468

we'll keep this ticket open until we confirm it with node team

**Comment by jrmanes** [comment]
syncing with node team

**Comment by jrmanes** [comment]
update:

confirmed with node team to keep these new metrics in celestia-node repo, as it's small, it's okay to keep it there
