### ISSUE TITLE
Expose Services LoadBalancers, Ingress - Names & IPs

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#425]
```[tasklist]
### Tasks
- [x] Get all the services in the NS(LB for now)
- [x] rbac - services
- [x] Deploy a service in a NS with permissions to get the services
- [x] Expose the services via OTEL
- [x] Ship metrics to Grafana Cloud
- [x] register metrics in prometheus - new metric called `load_balancers`
- [x] create dynamic table in grafana
- [x] move repo to celestiaorg
- [x] create tag
- [ ] https://github.com/celestiaorg/devops/issues/429
- [ ] https://github.com/celestiaorg/devops/issues/430
- [ ] https://github.com/celestiaorg/watchdog/issues/5
```

**Comment by jrmanes** [comment]
update:

the service it's running, I can get the LB ips, I'm setting up the OTEL collector to expose those LB via attributes (*similar approach as we did for `build_info`*)

**Comment by jrmanes** [comment]
deployed, it looks like:

<img width="918" alt="Screenshot 2023-07-25 at 13 52 15" src="https://github.com/celestiaorg/devops/assets/32740567/3fc452ac-c56c-4360-8ab4-16553083d951">

**Comment by jrmanes** [comment]
we solve this issue using [watchdog](https://github.com/celestiaorg/watchdog)
