### ISSUE TITLE
Arabica-Migrate secrets to 1Password

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#435]
```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/devops/issues/441
- [ ] https://github.com/celestiaorg/devops/issues/442
- [ ] https://github.com/celestiaorg/devops/issues/443
```

**Comment by jrmanes** [comment]
close as done
