### ISSUE TITLE
Talk to John - celestia-bot to 1Pass - *we'll remove the Matt token*

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#452]
```[tasklist]
### Tasks
- [x] talk to John - create his account and grant access
- [x] create a vault for the needed creds
- [x] create a new group called `Engineering Managers` - add EMs to it
- [x] create a new vault called `Engineering Managers` add the EMs group to it
- [x] use the celestia-bot creds in GitHub and remove the Matt's token
```

**Comment by Bidon15** [comment]
tagging @MSevey so we can better communicate our needs with the bot

**Comment by MSevey** [comment]
Here are the PATs that I have from my account and the access levels. 



![Image](https://github.com/celestiaorg/devops/assets/15232757/d0c23de3-70e3-4a75-a9e0-48a75e3e5639)


Here are the Celestia secrets that will need to be updated



![Image](https://github.com/celestiaorg/devops/assets/15232757/af7ed392-cf3e-4f12-bcae-a2c0fd7e5f80)


Here are the rollkit secrets



![Image](https://github.com/celestiaorg/devops/assets/15232757/01c5092a-6d91-4a71-bf60-6e64b1fc3473)

**Comment by MSevey** [comment]
We will need to add the bot account as an owner of celestia.
We should also just create a rollkit-bot github account that then is the owner of rollkit to keep concerns separate.

**Comment by MSevey** [comment]
We should also look at then moving Synk to those bot accounts so that all the Snyk PRs aren't being created by me @sysrex

**Comment by MSevey** [comment]
> @MSevey do we have any updates about rollkit?

All done on my end 👍

**Comment by jrmanes** [comment]
update:

we can close this as done
