### ISSUE TITLE
[EPIC] ITN Infrastructure

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#46]
## Introduction

We need to deploy a cluster that handles requests from participants during ITN 

The basic setup is shown in this repo with necessary repos:

https://github.com/celestiaorg/celestia-local-docker

## What to do: 

- [x] Deployment of otel-collector in k8s that can handle 1k+ LNs submitting PFBs
- [x] Postgres DB should be available to handle all the data that is produced by the otel-collector
- [x] Nodelogger 
- [x] Leaderboard backend
- [x] Grafana (for testing purposes)
   - [x] Prometheus data source
