### ISSUE TITLE
[EPIC] Alerting Infrastructure

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#484]
# Description 📑

Hello team!

In this Epic we are going to have all the tasks related to alerting, this was created from the main epic: 
[EPIC] Monitoring additional Resources](https://github.com/celestiaorg/devops/issues/121)

--- 

# Tasks 🔖
All the tasks that are needed can be found here:

```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/devops/issues/490
- [ ] https://github.com/celestiaorg/devops/issues/485
- [ ] https://github.com/celestiaorg/devops/issues/491
- [ ] https://github.com/celestiaorg/devops/issues/492
- [ ] https://github.com/celestiaorg/devops/issues/496
- [ ] https://github.com/celestiaorg/devops/issues/494
- [ ] https://github.com/celestiaorg/devops/issues/486
- [ ] https://github.com/celestiaorg/devops/issues/489
- [ ] https://github.com/celestiaorg/devops/issues/513
- [ ] https://github.com/celestiaorg/devops/issues/507
- [ ] https://github.com/celestiaorg/devops/issues/493
- [ ] https://github.com/celestiaorg/devops/issues/514
- [ ] https://github.com/celestiaorg/devops/issues/516
- [ ] https://github.com/celestiaorg/devops/issues/518
- [ ] https://github.com/celestiaorg/devops/issues/519
- [ ] https://github.com/celestiaorg/devops/issues/520
- [ ] https://github.com/celestiaorg/devops/issues/488
- [ ] https://github.com/celestiaorg/devops/issues/487
- [ ] https://github.com/celestiaorg/devops/issues/524
- [ ] https://github.com/celestiaorg/devops/issues/517
```

--- 

If you need to add more tasks or ideas, please, feel free to do it#121 

Cheers! 🚀 

Jose Ramon Mañes

**Comment by Bidon15** [comment]
closing as done. #517 will be done as a separate EPIC bc of diff grafana envs we have with diff use-cases and not only our bootstrappers
