### ISSUE TITLE
feat: Metrics and alarms by Namespace

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#486]
```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/devops/issues/504
- [ ] https://github.com/celestiaorg/devops/issues/503
- [ ] https://github.com/celestiaorg/devops/issues/502
```

**Comment by jrmanes** [comment]
update:

close as done
