### ISSUE TITLE
feat: Alarming if chains go down

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#488]
```[tasklist]
### Tasks
- [x] robusta
- [x] arabica
- [x] arabica-10
- [x] mocha
- [x] mainnet (just prepare them)
```

```[tasklist]
### Tasks
- [x] Consensus - validator height - non-validator (full-node)
- [x] DA - validator height - BN
- [x] DA - FN - BN
- [x] Cons - full height - BN - FN
```

**Comment by jrmanes** [comment]
testing with robusta-torch-1

**Comment by jrmanes** [comment]
testing phase, sending notifications to slack & pd

**Comment by Bidon15** [comment]
tested with mocha-4
