### ISSUE TITLE
Channels in Slack

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#491]
```[tasklist]
### Tasks
- [x] Robusta
- [x] Arabica
```

```[tasklist]
### Tasks
- [x] Send notifications to Slack - Robusta
- [x] Send notifications to Slack - Arabica
```

```[tasklist]
### Tasks
- [x] Renew token - Robusta
```

**Comment by jrmanes** [comment]
update:

robusta channel: `#alerts-infra-robusta`

**Comment by jrmanes** [comment]
update:

robusta channel: #alerts-infra-arabica
