### ISSUE TITLE
bug: Intermittent Node-to-Node Pod Communication Failure in Kubernetes Cluster

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#505]
Sometimes, pod communication between 2 nodes in k8s is not possible.

The reason still needs to be identified.

Restart of the nodes has fixed the issue so far.

So far, this was discovered randomly.

```[tasklist]
### Tasks
- [ ] Investigate the cause of that issue
- [ ] Create automation to get notified if this happens again
- [ ] Figure out proper bug resolution
```

**Comment by smuu** [comment]
I haven't seen this in a while. I assume that SCW fixed that issue.

Otherwise, we have gold support now, and in case this happens again, we can escalate immediately.
