### ISSUE TITLE
feat: pagerduty keys to 1pass

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#507]
```[tasklist]
### Tasks
- [x] secret with credentials
- [x] rotate old one
- [x] use it from secrets - remove hardcoded
- [x] ~email config from secrets - investigate it~
- [x] grafana alerts to pg
```

**Comment by jrmanes** [comment]
close as done
