### ISSUE TITLE
arabica-10

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#511]
```[tasklist]
### Tasks
- [x] deploy 1 Password manually
- [x] gp3 volumes
- [x] pyroscope
- [x] jaeger
- [x] torch
- [x] ingress
- [x] watchdog
- [x] external DNS
- [x] deploy consensus manually
- [x] deploy DA manually
- [x] peers txt in network repo
- [x] explorer
- [x] faucet
- [x] bump node repo - https://github.com/celestiaorg/celestia-node/pull/2639
- [x] grafana cockpit
- [x] proemtheus
- [x] alertmanager
- [x] app: celestia-app:v1.0.0-rc13
```

**Comment by jrmanes** [comment]
arabica-10 is up & running, all the tools are deployed correctly 
we can close this one as done

**Comment by jrmanes** [comment]
we can close this as done
