### ISSUE TITLE
feat: Grafana Alerts

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#516]
```[tasklist]
### Tasks
- [x] Slack Integration for Robusta
- [x] Slack Integration for Arabica
- [x] Slack Integration for Arabica-10
- [x] Slack Integration for Mocha
- [x] Slack Integration for Mainnet
```

```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/devops/issues/517
```

**Comment by jrmanes** [comment]
![Screenshot 2023-09-12 at 11 31 52](https://github.com/celestiaorg/devops/assets/32740567/08365236-c0ae-4f89-acd0-dd686443e79f)

**Comment by jrmanes** [comment]
close as done
