### ISSUE TITLE
cicd: Deployment to Dev env

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#52]
## Description 📜

Hello team,

The following ticket is created in order to create a pipeline to deploy to the different clusters via GitOps approach.
We can start deploying to dev cluster.

If you have more in mind, please, feel free to add them to the list 📝 

Thanks in advance!

--- 

### Some interesting articles 🔍

[argocd-image-updater](https://argocd-image-updater.readthedocs.io/en/stable/)

--- 

### Requirements 🔧 

- [x] Having ArgoCD installed in the clusters.
- [x] Connect ArgoCD to Github
- [x] Github Action needs to have permission to read/write to the repos
- [x] ArgoApp -> WIP https://github.com/celestiaorg/devops/issues/79

--- 

### Tasks 🔖

- [ ] Create Github actions to be triggered when there will be a new tag. -> or *argocd image updater*
- [ ] The action writes to the ArgoCD's repository (which Argo is connected)
- [ ] ArgoCD deploys the new tag to the cluster.
  - [ ] @devops-team -> *we have to discuss if we want to deploy automatically to the clusters or we want to wait and click to deploy.*

--- 

### Repositories 🗂️

- [argocd-apps](https://github.com/celestiaorg/argocd-apps/)
- [celestia-node](https://github.com/celestiaorg/celestia-node)
- [celestia-app](https://github.com/celestiaorg/celestia-app)
 
---

#### Issues 👨‍🔧

Closes: https://github.com/celestiaorg/devops/issues/79

--- 

PS: *Please, feel free to update any part of the ticket, any suggestion/idea is always welcome* 😊 

---

Best 🚀 

Jose Ramon Mañes

**Comment by smuu** [comment]
I propose using https://argocd-operator.readthedocs.io/en/latest/ for setting up and managing ArgoCD

**Comment by Bidon15** [comment]
Grooming 10/03/2023: @smuu @jrmanes can you link the argo-cd repo to this issue and mark in todo what is done?

**Comment by smuu** [comment]
When running multiple Kubernetes Cluster and using ArgoCD as the GitOps tools, we have multiple ways to implement this.

1. Having one ArgoCD instance in a 'management cluster' managing all Kubernetes Clusters
2. Having an ArgoCD in each Kubernetes Cluster
    1. Manage the ArgoCD instances separately
    2. Have an ArgoCD instance that manages the ArgoCD instances in the Clusters

There are different topics to consider here:

1. Ease of management
2. Dependencies between different Clusters (staging)
3. Uptime of 'management cluster' and ArgoCD instances

**Comment by Bidon15** [comment]
Closing as done
