### ISSUE TITLE
arabica: store block history of BNs

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#523]
## Description 🧾
 
hello team!

based on our discussion here: [link](https://celestia-team.slack.com/archives/C04MKGKSU9H/p1694615087520079)

we have to consider backing up the block history for some BNs

---

## Goal 🎯

Backup the block history of BNs and upload it to s3

---

## How to do it?: 📝

```[tasklist]
### Tasks
- [x] Create the s3/ObjStorage in the project
- [x] Create credentials for the service
- [ ] Stop the service [use this patch](https://github.com/celestiaorg/celestia-stack-internal/blob/main/consensus/environment/arabica-9/full-1/patches/statefulset.yaml#L19-L33)
- [ ] Access to the node
- [ ] Create the tar
- [ ] Remove the STS (we'll keep the PVCs)
- [ ] Mount the data pvc to another pod with root permissions
- [x] Install aws cli
- [x] Install `scw` tool and configure the credentials
- [x] Add the scw config - generate it via data in the secrets
- [x] mount the `scw` secret to grant permissions to the pod
- [x] Upload the file to the bucket
```

---

## Useful links:

- [overide the entrypoint](https://github.com/celestiaorg/celestia-stack-internal/blob/main/consensus/environment/arabica-9/full-1/patches/statefulset.yaml#L19-L33)
- [scw-config](https://www.scaleway.com/en/docs/storage/object/api-cli/object-storage-aws-cli/)

--- 

## Config files: 📜

`~/.aws/config`

```
[plugins]
endpoint = awscli_plugin_endpoint
cli_legacy_plugin_path = <your-local-path>

[default]
region = nl-ams # s3 region
s3 =
  endpoint_url = https://<bucket-name>.s3.nl-ams.scw.cloud/
  signature_version = s3v4
  max_concurrent_requests = 100
  max_queue_size = 1000
  multipart_threshold = 50 MB
  multipart_chunksize = 10 MB
s3api =
  endpoint_url = https://s3.nl-ams.scw.cloud/
```

**Comment by Bidon15** [comment]
We should start with bridge-20 and go downwards afterwards, leaving only 10 bridge nodes running

**Comment by Bidon15** [comment]
in addition, bridge 1 and 2 IIRC are running out of storage, so we should reallocate the storage capacity to them as part of this task

**Comment by jrmanes** [comment]
bucket: [arabica-9-storage](https://console.scaleway.com/object-storage/buckets/nl-ams/arabica-9-storage/explorer)

**Comment by jrmanes** [comment]
keys `arabica-9-storage-creds`

**Comment by jrmanes** [comment]
resources preparation: WIP -> [storage-backup-migrator](https://github.com/celestiaorg/celestia-internal-tools/tree/jose/backup-storage-s3/tools/storage-backup-migrator)

**Comment by jrmanes** [comment]
able to upload files from the pod

**Comment by jrmanes** [comment]
aws s3 cp test-from-pod s3://arabica-9-storage
upload: ./test-from-pod to s3://arabica-9-storage/test-from-pod


![Screenshot 2023-09-20 at 17 06 18](https://github.com/celestiaorg/devops/assets/32740567/f175ed3b-a90d-4d44-b8db-2aeee134748e)

**Comment by jrmanes** [comment]
we can close it as done 👌
