### ISSUE TITLE
tf: specify region/zone to the node-pools

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#526]
based on the current situation with SCW, we need to have the choice to deploy the node pools to an specific region/zone.

this task is to update the tf module: [terraform-module-scw-k8s](https://github.com/celestiaorg/terraform-module-scw-k8s/tree/main), to allow us to do so.

useful links:
- https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/k8s_pool
- https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/guides/regions_and_zones#regions
```[tasklist]
### Tasks
- [ ] update the tf module
- [ ] add the feature to specify the node-pools + a default one
- [ ] create a new release
- [ ] update the current clusters to use the new version, specifing the regions/
```
