### ISSUE TITLE
qbg: deploy to robusta - arabica - mocha

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#529]
Create the resources and deploy them to arabica (first) and mocha:

![Image](https://github.com/celestiaorg/devops/assets/32740567/8ffef35f-f699-4dc7-85e1-b69f6d851d24)

```[tasklist]
### Tasks
- [x] sts x4
- [x] 2 volumes - `keystore` and `data`
- [x] svc - clusterip
- [x] resources 1cpu/1ram
- [x] init container
- [ ] https://github.com/celestiaorg/devops/issues/531
- [ ] https://github.com/celestiaorg/devops/issues/532
- [x] improt the evms
- [ ] deploy to arabica
- [ ] deploy to mocha
```

**Comment by jrmanes** [comment]
https://github.com/celestiaorg/celestia-stack-internal/tree/jose/robusta-qgb-res/qgb
