### ISSUE TITLE
create evms address from metamask and store the data - evm + pass to 1pass

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#532]
```[tasklist]
### Tasks
- [x] use metamask to create the evm
- [x] store the values in 1pass
- [x] create a secret
- [x] bind the evm to the validator of the network
- [x] import it
```

**Comment by jrmanes** [comment]
we can close this as done
