### ISSUE TITLE
blobstream: finish migration to arabica-10

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#567]
Arabica-10 contains rc2 of blobstream in a separate branch of stack.
We need to prepare the PR and merge to main branch, so blobstream integration is considered done

```[tasklist]
### Tasks
- [ ] finish the branch into a PR for celestia-stack
- [ ] bump the version of arabica-10 for new blobstream
- [ ] for robusta, let's migrate to sepolia too (don't use the same EVM account from arabica-10 for robusta in the relayer)
- [ ] a new branch with robusta
```
