### ISSUE TITLE
dashboards: a dashboard to track validators' da bridge nodes as part of any programm

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#568]
We need to track the validators who are running da bridge nodes

In order to achieve this, we need to come up with a tool that: 

```[tasklist]
### Tasks
- [ ] Reads existing peerIDs in the prometheus server
- [ ] Compares received peerIDs with ones in the DB that is getting updated
- [ ] Makes a new metric that is formed around the peerId and name of the validator
- [ ] A validator can have multiple peerIDs
- [ ] Make a filter that takes into account peerIDs from a DB for metrics aggregation
```

**Comment by Bidon15** [comment]
Needs some input from devrel and validators on the list
