### ISSUE TITLE
[EPIC] Cleanup Q4

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#584]
Based on [this](https://www.notion.so/celestiaorg/Q4-23-retro-planning-275e4db6a2cb418b90f8682e6130f715)

I have created some issues to keep track of them.

Feel free to assign them to you and add any task you consider.

Cheers! 🚀 

```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/devops/issues/586
- [ ] https://github.com/celestiaorg/devops/issues/587
- [ ] https://github.com/celestiaorg/devops/issues/588
- [ ] https://github.com/celestiaorg/devops/issues/589
- [ ] https://github.com/celestiaorg/devops/issues/594
- [ ] https://github.com/celestiaorg/devops/issues/593
- [ ] https://github.com/celestiaorg/devops/issues/609
- [ ] https://github.com/celestiaorg/devops/issues/624
- [ ] https://github.com/celestiaorg/devops/issues/595
- [ ] https://github.com/celestiaorg/devops/issues/590
- [ ] https://github.com/celestiaorg/devops/issues/592
- [ ] https://github.com/celestiaorg/devops/issues/591
```

cc: @celestiaorg/devops

**Comment by smuu** [comment]
Closed and moved open issues to: https://github.com/celestiaorg/devops/issues/740
