### ISSUE TITLE
sre → autodevops → rename/create a new one

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#594]
```[tasklist]
### Tasks
- [ ] create new repo
- [ ] move resources
- [ ] test GA - create, remove, update
- [ ] notify teams
- [ ] archive old repo
```
