### ISSUE TITLE
[EPIC] Improvements/Refactors Q4

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#596]
Based on [this](https://www.notion.so/celestiaorg/Q4-23-retro-planning-275e4db6a2cb418b90f8682e6130f715)

I have created some issues to keep track of them.

Feel free to assign them to you and add any task you consider.

Cheers! 🚀 

```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/devops/issues/498
- [ ] https://github.com/celestiaorg/devops/issues/597
- [ ] https://github.com/celestiaorg/devops/issues/601
- [ ] https://github.com/celestiaorg/devops/issues/606
- [ ] https://github.com/celestiaorg/devops/issues/598
- [ ] https://github.com/celestiaorg/devops/issues/602
- [ ] https://github.com/celestiaorg/devops/issues/603
- [ ] https://github.com/celestiaorg/devops/issues/600
- [ ] https://github.com/celestiaorg/devops/issues/599
- [ ] https://github.com/celestiaorg/devops/issues/604
- [ ] https://github.com/celestiaorg/devops/issues/605
- [ ] https://github.com/celestiaorg/devops/issues/607
```

cc: @celestiaorg/devops

**Comment by smuu** [comment]
Closes and moved open issues to: https://github.com/celestiaorg/devops/issues/740
