### ISSUE TITLE
testground/networking: Bit Twister

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#608]
testground-sidecar utilises weave, aws-cni which causes a lot of headaches for test runners, thus we need to get out of it. 
As part of this POC, we need to hack cilium library to get a more stable internet connection / ip allocation for test pods 

```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/bittwister/issues/1
- [ ] https://github.com/celestiaorg/bittwister/issues/4
- [ ] https://github.com/celestiaorg/bittwister/issues/9
- [x] Add Jitter to the network
- [x] Add CLI to the tool
- [ ] https://github.com/celestiaorg/bittwister/issues/3
- [x] Add asutomatic tests to test all 5 functions
```

**Comment by mojtaba-esk** [comment]
quick update: figured out the Cilium does not do what we want out of box. But it gives us a clue where to proceed. It uses eBPF under the hood to do its job at linux kernel. To manipulate network traffic at the kernel level, we need to use XDP (eXpress Data Path). Right now I am learning it.

**Comment by smuu** [comment]
Agreed with @mojtaba-esk that this can be closed
