### ISSUE TITLE
[EPIC]: testnets migration to blockstorage v2

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#638]
```[tasklist]
### Tasks
- [ ] Recreate a new cluster for robusta using block-storage v2
- [ ] Run a robusta chain that adds load for 2-3 days
- [ ] If all good, migrate arabica-10 to the new cluster with v2
- [ ] Same for mocha
```

**Comment by sysrex** [comment]
I blocked this task for a bit until we figure out other side conversations with the provider

**Comment by smuu** [comment]
arabica-11 is deployed with blockstorage v2
