### ISSUE TITLE
knuu/bittwister: write a sample test that proofs that network condition setups work

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#641]
This issue is marked as done after the following tasks have been achieved

```[tasklist]
### Tasks
- [ ] Setup a knuu-example test run that spins up 3 containers that send files to each other
- [ ] The test should include scenarios like bandwidth, latency, jitter, packet loss per testable container
- [ ] Setup a new celestia-app validators chain of 4 in knuu
- [ ] Verify block production can be unstable with lowering bandwidth per each of the validator and increasing it back to normal.
- [ ] Same goes with latency, jitter, packet loss dynamism 
```

@mojtaba-esk ,please consult @smuu about knuu 🙏

**Comment by Bidon15** [comment]
If you want, you can use txsim that core/app team has created to fill in the blocks during knuu run of 4 validators chain. This can help load up the gossiping part with limited network conditions, thus creating difficulties for validators

**Comment by mojtaba-esk** [comment]
Thanks yes `txsim` will come handy in our tests

**Comment by mojtaba-esk** [comment]
It seems like that all what is required in this issue is implemented. Can we close it?
@Bidon15 @smuu
