### ISSUE TITLE
[MEGA-EPIC] Q1 2024

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#667]
```[tasklist]
### Tasks
- [ ] [EPIC] Improve sync-service
- [ ] [EPIC] Operator to build images in cluster
- [ ] [EPIC] Documentation
- [ ] [EPIC] Create and start tests from snapshots
- [ ] [EPIC] Support for assertions of logs and metrics
- [ ] [EPIC] Move to a more reliant Kubernetes setup
- [ ] [EPIC] Prep onsite
- [ ] [EPIC] Improve observability in testing
- [ ] Support
- [ ] On-call
```
