### ISSUE TITLE
Deploy arabica-11

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#692]
**Consensus**
version: `v1.3.0`
memory: `8Gi`
cpu: `1750m`
storage: `500G` (v2)
#validator: `4`
#full: `0` (not needed)
snapshot node: `yes`

**DA**
version: `v0.12.1`
memory: `6Gi`
cpu: `1750m`
storage: `500G` (v2)
#bridge: `4` (bootstrapper mode)
#full: `0` (as 4 bridges connected to 4 validator)
snapshot node: `yes`

```[tasklist]
### Tasks
- [x] Figure out how to set up a multi validator setup
- [x] Create tf for the new chain - node-pools (same types as mocha)
- [x] Deploy new k8s cluster with tf
- [x] Deploy and configure 1pass operator
- [x] Deploy observability stack from stack-internal
- [x] Deploy torch from stack-internal
- [x] Create kustomization files in stack-internal (see [comment](https://github.com/celestiaorg/devops/issues/692#issuecomment-1855487077) about validator)
- [x] Create snapshot job in internal-tools
- [x] Add the new chain to argocd
- [x] Deploy faucet and Explorer
- [x] Create PR for celestia-node with DA multiaddresses
- [x] Provide devrel with all the endpoints
- [x] Notify dymension
- [ ] notify keplr
- [x] check if snapshot creation was succesfull
- [ ] check if alertmanager is working
```

**Comment by Bidon15** [comment]
To not repeat the same mistakes we have with arabica9/10, we need 4 validators instead of 1

Thus, we can eliminate the consensus full nodes

**Comment by Bidon15** [comment]
One way of achieving this is to create 1 validator with a lot of tokens and 3 consensus full nodes, then promote all 3 to validators with equal supply across 4 nodes. Bridge nodes can connect to each of them
