### ISSUE TITLE
Decrease usage of disk to 1TB in lunar

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#693]
```[tasklist]
### Tasks
- [x] Create a temporary new node to check if starting from the snapshot is going (DA and consensus)
- [x] Delete node (also PVC)
- [x] Recreate node with less storage (1TB)
- [x] Wait until the node started from snapshot and is sync to the tip of chain
```
