### ISSUE TITLE
harden lunar setup

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#696]
```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/devops/issues/697
- [ ] https://github.com/celestiaorg/devops/issues/699
- [ ] https://github.com/celestiaorg/devops/issues/701
- [ ] https://github.com/celestiaorg/devops/issues/703
- [ ] https://github.com/celestiaorg/devops/issues/698
- [ ] https://github.com/celestiaorg/devops/issues/700
- [ ] https://github.com/celestiaorg/devops/issues/704
- [ ] https://github.com/celestiaorg/devops/issues/702
- [ ] https://github.com/celestiaorg/devops/issues/705
```

**Comment by smuu** [comment]
can be closed because it's done or moved to another ticket to track
