### ISSUE TITLE
[EPIC] Improve alerting

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#724]
**Problems**
- on-call employees get alerts via PD that are false positives
- alerting rules are part of the AM config

```[tasklist]
### Tasks
- [ ] Understand why false positives are sent and fix it (SCW network issues?)
- [ ] Use PrometheusRule CRD for alerts (consider creating a separate repo)
- [ ] Use PrometheusRule CRD for custom metrics used in HPA (consider creating a separate repo)
```
