### ISSUE TITLE
[EPIC] Cleanup/Refactorting Q1-2024

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#740]
```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/devops/issues/592
- [ ] https://github.com/celestiaorg/devops/issues/591
- [ ] https://github.com/celestiaorg/devops/issues/600
- [ ] https://github.com/celestiaorg/devops/issues/599
- [ ] https://github.com/celestiaorg/devops/issues/604
- [ ] https://github.com/celestiaorg/devops/issues/605
- [ ] https://github.com/celestiaorg/devops/issues/607
```
