### ISSUE TITLE
k8s: Dynamically get trusted_peers

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#78]
## Description 📜

Hello team,

The following ticket is created in order to add some improvements to our Kubernetes resources and deployment flow.
 
ℹ  *Currently for the Robusta network, though the resources will be shared among the other networks in future*

### Current status:

Some context, deploying any chain from scratch (currently Robusta) to K8S, there is a manual process that we have to follow (not very fancy...)
You can see it here: [link](https://github.com/celestiaorg/celestia-stack/blob/jose/celestia-app-full/data-availability/overlays/robusta-1/kustomization.yaml#L34)

The steps are:

1. Deploy the bridge
2. Check the bridge's logs and get the ID
3. Modify it to the ENV var and deploy it again
4. For the full nodes, deploy them, check the id, modify the ENV var and deploy them again

Summarising, it takes a while until you have the new chain up & running, and also, it's a manual process so making a mistake is a reality...

### Desire state

No manual steps are involved in the process to spinning up a new chain, it has to be autonomous, just deploy the services and they manage themselves.

### How to achieve it?

After some research, we've found that we have to create a small service that manages this part, we tried to do it using DNSs and we couldn't make it work, the process is too long, we depend on the provider, etc...

Another alternative that we found is:

Small Go service manages the mutual peers automatically, meaning that when the nodes start, they check the trusted peers values and if they don't have them, they ask the service in order to generate them.

That service connects to them and gets the information by checking their API and generating the addresses on the nodes.
Then, it restarts them and they will do the process again, they start, check the value and if they have it, just continue, otherwise they contact this service asking for the addresses.

### There are some ideas to avoid this manual process

For example:
- ~libp2p can resolve multiaddresses from a DNS TXT record:~ https://github.com/multiformats/multiaddr/blob/master/protocols/DNSADDR.md
- ~We could have a ConfigMap for coredns that contains a DNS TXT record pointing to the nodes:~ https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/

Personally, I do like this idea, but we will have to keep in mind some topics:
- This service has to be OSS, because everybody who will try to deploy the services in K8S will face the same issue
- It has to be easy to manage, this service has to do only one thing and doing it well.

*We tested and it doesn't work....*

### How to implement it?

💡  I'll use the [client-go library](https://github.com/kubernetes/client-go) for getting the data from the K8S API and execute the actions depending on the results.

If you have more in mind, please, feel free to add them to the list 📝 

Thanks in advance!

--- 

### Some interesting articles 🔍

[client-go](https://github.com/kubernetes/client-go)
[kubernetes-dns](https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/)
[libp2p-multiaddresses](https://github.com/multiformats/multiaddr/blob/master/protocols/DNSADDR.md)

--- 

```[tasklist]
### Tasks 🔖
- [ ] https://github.com/celestiaorg/devops/issues/341
- [ ] https://github.com/celestiaorg/devops/issues/344
- [ ] https://github.com/celestiaorg/devops/issues/343
- [ ] https://github.com/celestiaorg/devops/issues/342
- [ ] https://github.com/celestiaorg/devops/issues/349
- [ ] https://github.com/celestiaorg/devops/issues/352
- [ ] https://github.com/celestiaorg/devops/issues/361
```
--- 

### Repository 🗂️

*probably a new one*

- [ ]()

--- 

PS: *Please, feel free to update any part of the ticket, any suggestion/idea is always welcome* 😊 

---

Best 🚀 

Jose Ramon Mañes

**Comment by jrmanes** [comment]
Hello @celestiaorg/devops 

I've created this ticket and assigned it to all of us, but it's just to have everybody aligned.

This is not super critical, but it will be good to have it  and I have not move it to any sprint yet 📝 

We need to discuss it a little bit before start implementing it and find the best approach

Best! 🚀 

Jose Ramon Mañes

**Comment by jrmanes** [comment]
update:

the generation is okay, it's pending to spread the config between the peers and restart them

**Comment by jrmanes** [comment]
close as done ✅
