### ISSUE TITLE
snapshot: DA Light nodes as a public good

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#802]
If someone wants to have a light node to be usable asap, syncing and dasing historical blocks might stop them from doing so. 
Even with pruning enabled, we might see that devX is not going to be good enough. 
Thus having a snapshot for light nodes is beneficial to reduce the amount of waiting for devs who experiment a lot with rollup development using celestia da light node

```[tasklist]
### Tasks
- [ ] Snapshot arabica-11 light node with full historical data once every week
- [ ] Snapshot arabica-11 light node with recency window (pruning enabled) once every week
- [ ] Snapshot mocha-4 light node with full historical data once every week
- [ ] Snapshot mocha-4 light node with recency window (pruning enabled) once every week
```

**Comment by Bidon15** [comment]
Example can be watched here 
https://da-light-data.s3.nl-ams.scw.cloud/mocha/06-02-2024.tgz
