### ISSUE TITLE
docker: Security - Slack notification in case of CVEs

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#81]
## Description 📜

Hello team,

The following ticket is created in order to add security during our supply chain for our Docker images.

ℹ️ Low priority

As you may know I've been working on the CI part, adding some new features, one of the was [Trivy](https://www.aquasec.com/products/trivy/) which is a tool that help us for scanning our Docker images and provide us a summary.

The idea behind this ticket is to connect our Slack (we'll have to create a channel for it), to Github and send a notification to it in case that during the CI, Trivy detects any CVE or potential bug.
After this, we'll have to go and fix it.

A CVE example:

![Image](https://user-images.githubusercontent.com/32740567/215786916-f18f6664-c79f-477e-bf4a-9986a509f86b.png)

If you have more in mind, please, feel free to add them to the list 📝 

Thanks in advance!

--- 

### Some interesting articles 🔍

Why is this important?
If we have a CVE(Common Vulnerabilities and Exposures), that means that our code is vulnerable and our services are exposed to be hacked/hijacked.
From my prospective, it's better to be "a little paranoid" in some way and be proactive in the security field.

[what is a CVE](https://www.redhat.com/en/topics/security/what-is-cve)

--- 

### Tasks 🔖

- [ ] Create Slack channel for this/discuss with the team which one will be find to use.
- [ ] Test it.

Check: https://github.com/celestiaorg/devops/issues/55

Next steps/nice to have:
- [ ] Update the Github Action to block the build, currently is just informative.

--- 

### Repository 🗂️

- [ ] [celestia-node](https://github.com/celestiaorg/celestia-node)
- [ ] [celestia-app](https://github.com/celestiaorg/celestia-app)

---

#### Issues 👨‍🔧

Closes: 

--- 

PS: *Please, feel free to update any part of the ticket, any suggestion/idea is always welcome* 😊 

---

Best 🚀 

Jose Ramon Mañes

**Comment by jrmanes** [comment]
Grooming 10/03/2023: this needs to be discuss in the same mindset / context that we have here:
https://github.com/celestiaorg/devops/issues/55

https://github.com/celestiaorg/test-infra/issues/161#issuecomment-1463662909

**Comment by smuu** [comment]
Idea: Installing a tool that runs trivy scan on all running containers in the Kubernetes cluster periodically. We then can maybe use metrics, together with a dashboard and alerts to get aware of new CVEs.

**Comment by jrmanes** [comment]
> Idea: Installing a tool that runs trivy scan on all running containers in the Kubernetes cluster periodically. We then can maybe use metrics, together with a dashboard and alerts to get aware of new CVEs.

i do love it!

**Comment by smuu** [comment]
Closed because of Snyk
