### ISSUE TITLE
MSevey/workflows v0.3.3 Release Deployment

### ISSUE THREAD

**Issue by MSevey** [celestiaorg/devops#849]
## Release Checklist
```[tasklist]
### Pre-work
- [ ] Confirm release tested on Robusta
- [ ] App and Node compatibility confirmed
- [ ] Release notes reviewed
```
```[tasklist]
### Stage 1: Arabica
- [ ] Prepare deployment to Arabica
- [ ] Prepare announcement for Arabica
- [ ] Announce release for Arabica
- [ ] Deploy to Arabica
- [ ] Verify release on Arabica
- [ ] Docs updated for release for Arabica
```
```[tasklist]
### Stage 2: Mocha
- [ ] Prepare deployment to Mocha
- [ ] Prepare announcement for Mocha
- [ ] Announce release for Mocha
- [ ] Deploy to Mocha
- [ ] Verify release on Mocha
- [ ] Docs updated for release for Mocha
```
```[tasklist]
### Stage 3: Mainnet
- [ ] Prepare deployment for mainnet
- [ ] Prepare announcement for mainnet
- [ ] Announce release for mainnet
- [ ] Deploy to mainnet
- [ ] Verify release on mainnet
- [ ] Docs updated for release for mainnet
```
